### ISSUE TITLE
[BUG] `Component` header and Freetext Value cause exception

### ISSUE THREAD

**Issue by omaus** [nfdi4plants/arc-to-invenio#19]
**Describe the bug**
[ValidateAgainstHeader](https://github.com/nfdi4plants/ARCtrl/blob/5af193cf5d70881b9c21772bf306df172853d6a5/src/Core/Table/CompositeCell.fs#L172) causes an error in everyday usecase.

**To Reproduce**
1. Create new ARC
2. Fill out investigation metadata
4. Create study and fill out metadata
5. Test pipelines, should pass
6. Add new metadata sheet to study and add `Component` building block
7. Test pipeline, should succeed
8. Add a row to your `Component` building block
9. Test pipeline, pipeline fails with metadata error
10. Change component to something else, e.g. `Characteristics`
11. Pipeline succeeds

**Expected behavior**
Everyting's fine.

**OS and framework information (please complete the following information):**
 - OS: Win10
 - OS Version: Pro 64-bit (10.0, Build 19045)

**Additional context**
[Full history of the bug occurence](https://github.com/nfdi4plants/arc-validate/issues/112).

**Comment by HLWeil** [comment]
Okay so the Issue should fixed.

@SabrinaZander @Hannah-Doerpholz would be great if you could confirm

**Comment by HLWeil** [comment]
Maybe you could invite me to the ARC @SabrinaZander, so I can have a look?

**Comment by Hannah-Doerpholz** [comment]
Since I have the same issue in my test ARC I invited you to that one if that helps. There is no "secret" data in that one @HLWeil

**Comment by HLWeil** [comment]
Okay after some more investigation, it seems like this is not a problem of any of the source code. 

Instead, the docker packaging of the tool does not work as intended, i.e. calling the tool fails. 

Which also becomes apparent in the image you posted: 

<img width="248" alt="Image" src="https://github.com/user-attachments/assets/05086a49-fe35-41ba-98ea-4baf3f6a51c7" />

**Comment by HLWeil** [comment]
Should be fixed with https://github.com/nfdi4plants/arc-to-invenio/commit/0f4fba806d3ceaa300043136b971f0b6b5bcfcae

@Hannah-Doerpholz, I restarted your pipeline and it ran through. @SabrinaZander, could you also check?

**Comment by Hannah-Doerpholz** [comment]
It ran through for my actual "data" ARC as well. Thank you!

**Comment by SabrinaZander** [comment]
Thank you very much, in my test ARC the pipeline runs successfully.
In another ARC, in which I first encountered the metadata pipeline problem, there is still an error. 
Now called internal error:

 If you would like to investigate this further, I would be happy to invite you. It is no longer relevant for me, as we have already remade the ARC and published it.

**Comment by HLWeil** [comment]
Yeah, I'll take a look!

**Comment by HLWeil** [comment]
Okay, this problem is actually a mismatch between the strictness of the validation and the conversion, regarding the information in the contacts.

1. Validation passes if `at least one` person has all required fields*
2. Converter requires `all` persons to have the required fields

In this case here one person was missing the `affiliation` property. 

So, in principle the goal will be to align both tools to follow the same rules. I don't want to decide on which of the two approaches to take by myself, so I'll move this to a discussion.

-------
*Required fields
- First Name
- Last Name
- E-Mail
- Affiliation

**Comment by HLWeil** [comment]
https://github.com/orgs/nfdi4plants/discussions/10
